renaming executable - enhancing log messages - introduce basic error handling - refactor brew parts to fit v4 of homebrew, removing cask distinction from upgrade process as it's included in 'brew upgrade' now

diff --git a/mac-update b/mac-update
--- a/mac-update
+++ b/mac-update
@@ -1,27 +1,55 @@
 #!/bin/bash
 #
-# update mac os for 
-# - packages installed by brew
-# - packages installed by mas
-# - packages installed by mac os system
+# Update macOS for:
+# - Packages installed by brew
+# - Packages installed by mas
+# - macOS system packages
 
-## brew
-echo -e "---\033[0;32m brew: update package reference \033[0m---"
-brew update
-echo -e "---\033[0;32m brew: update packages \033[0m---"
-brew upgrade
-echo -e "---\033[0;32m brew: upgrade packages \033[0m---"
-reinstallme=$(brew outdated --cask | awk '{print $1}')
-for i in $reinstallme; do brew cask reinstall "$i"; done
-echo -e "---\033[0;32m brew: cleanup old packages \033[0m---"
-brew cleanup
+# Function to display section headers
+print_header() {
+    echo -e "\n\033[1;34m$1\033[0m"
+    echo -e "--------------------------------------------------"
+}
 
-## mas
-echo -e "---\033[0;32m mas: list outdated mac app store packages \033[0m---"
+# Function to display success messages
+print_success() {
+    echo -e "\033[1;32m$1\033[0m"
+}
+
+# Function to handle errors
+handle_error() {
+    echo -e "\033[0;31mError encountered: $1. Exiting.\033[0m"
+    exit 1
+}
+
+# Update and upgrade Homebrew packages
+print_header "Updating Homebrew Packages"
+brew update  || handle_error "brew update failed"
+print_success "brew update completed successfully"
+
+print_header "Upgrading Homebrew Packages"
+brew upgrade  || handle_error "brew upgrade failed"
+print_success "brew upgrade completed successfully"
+
+print_header "cleanup Homebrew Packages"
+brew cleanup --prune=all  || handle_error "brew cleanup failed"
+print_success "brew cleanup completed successfully"
+
+print_header "autoremove outdated Homebrew Packages"
+brew autoremove  || handle_error "brew autoremove failed"
+print_success "brew autoremove completed successfully"
+
+
+# mas updates
+print_header "mas: list outdated Mac App Store packages"
 mas outdated
-echo -e "---\033[0;32m mas: upgrade outdated mac app store packages \033[0m---"
-mas upgrade
+print_success "mas outdated completed successfully"
 
-## mac os 
-echo -e "---\033[0;32m system: check for mac OS updates \033[0m---"
-softwareupdate -l 
+print_header "mas: upgrade outdated Mac App Store packages"
+mas upgrade
+print_success "mas upgrade completed successfully"
+
+# macOS system updates
+print_header "system: check for macOS updates"
+softwareupdate -l
+print_success "macOS updates check completed successfully"
